import numpy as np

probe_dict = {'SC6-1': 0,
              'SL10-2':1,
              'SL15-4':1}

study_dict = {'US BIOPSY LIVER NONFOCAL': ['liver', 'abdomen'],
 'US BIOPSY LIVER FOCAL': ['liver', 'abdomen'],
 'US LYMPH NODE BIOPSY': ['soft tissue', 'nodule'],
 'US BIOPSY KIDNEY NONFOCAL (EITHER SIDE)': ['kidney', 'abdomen'],
 'US PARACENTESIS THERAPEUTIC': ['abdomen', 'drainage'],
 'US BIOPSY TRANSPLANTED KIDNEY': ['kidney', 'abdomen'],
 'US PARACENTESIS DIAGNOSTIC AND THERAPEUTIC': ['abdomen', 'drainage'],
 'US THYROID BIOPSY': ['thyroid', 'nodule'],
 'US PARACENTESIS DIAGNOSTIC': ['abdomen', 'drainage'],
 'US THORACENTESIS DIAGNOSTIC AND THERAPEUTIC': ['chest', 'drainage'],
 'US THYROID ASPIRATION/FNA': ['thyroid', 'nodule'],
 'US DRAINAGE INTERVENTION NOT OTHERWISE SPECIFIED': ['soft tissue',
  'drainage'],
 'US DRAINAGE ABDOMEN': ['abdomen', 'drainage'],
 'US DRAINAGE GALLBLADDER (CHOLECYSTOSTOMY)': ['abdomen', 'drainage'],
 'US THORACENTESIS THERAPEUTIC (RIGHT)': ['chest', 'drainage'],
 'US THORACENTESIS THERAPEUTIC (LEFT)': ['chest', 'drainage'],
 'US BIOPSY MESENTERY': ['abdomen', 'drainage', 'soft tissue'],
 'US NECK SOFT TISSUE BIOPSY': ['soft tissue', 'nodule'],
 'US DRAINAGE CATHETER PLACEMENT': ['soft tissue', 'drainage'],
 'US DRAINAGE PELVIS': ['abdomen', 'drainage'],
 'US SOFT TISSUE BIOPSY': ['soft tissue', 'nodule'],
 'US BIOPSY KIDNEY NONFOCAL (LEFT)': ['kidney', 'abdomen'],
 'US CHEST TUBE PLACEMENT (RIGHT)': ['chest', 'drainage'],
 'US BIOPSY NOT OTHERWISE SPECIFIED': ['soft tissue', 'nodule', 'drainage'],
 'US ABDOMINAL PELVIC BIOPSY NOT OTHERWISE SPECIFIED': ['soft tissue',
  'nodule',
  'drainage'],
 'US CHEST TUBE PLACEMENT (LEFT)': ['chest', 'drainage'],
 'CT BIOPSY LIVER FOCAL': ['liver', 'abdomen'],
 'US BIOPSY KIDNEY FOCAL (LEFT)': ['liver', 'abdomen'],
 'US ASPIRATION ABDOMINAL COLLECTION': ['abdomen', 'drainage'],
 'CT LYMPH NODE BIOPSY': ['soft tissue', 'nodule'],
 'US DRAINAGE LIVER': ['liver', 'drainage', 'abdomen'],
 'US BIOPSY RETROPERITONEUM': ['abdomen'],
 'US LYMPH NODE ASPIRATION/FNA': ['soft tissue', 'nodule', 'drainage'],
 'US SOFT TISSUE ASPIRATION': ['soft tissue', 'drainage'],
 'US ASPIRATION PELVIS': ['abdomen', 'drainage'],
 'US THORACENTESIS DIAGNOSTIC (RIGHT)': ['chest', 'drainage'],
 'US THORACENTESIS DIAGNOSTIC (LEFT)': ['chest', 'drainage'],
 'US DRAINAGE KIDNEY/PARARENAL (RIGHT)': ['abdomen', 'kidney', 'drainage'],
 'US HEAD/NECK INTERVENTION NOT OTHERWISE SPECIFIED': ['soft tissue'],
 'US BIOPSY KIDNEY FOCAL (RIGHT)': ['kidney', 'abdomen'],
 'CT ABDOMINAL PELVIC BIOPSY NOT OTHERWISE SPECIFIED': ['abdomen'],
 'US DRAINAGE KIDNEY/PARARENAL (LEFT)': ['kidney', 'abdomen'],
 'IR PARACENTESIS (THERAPEUTIC)': ['abdomen', 'drainage'],
 'US PSEUDOANEURYSM THROMBIN INJECTION': ['soft tissue', 'nodule'],
 'IR PARACENTESIS (DIAGNOSTIC AND THERAPEUTIC)': [],
  np.nan: []}
